# Use root/example as user/password credentials
version: '3.7'

services:
  mariadb:
    image: mariadb:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: smsfactor
    ports:
      - 3307:3306
    volumes:
      - my-mariadb:/var/lib/mysql

  adminer:
    image: adminer
    restart: always
    ports:
      - 8081:8080

volumes:
  my-mariadb:

